create table Category (cateID int identity not null, status bit, cateName varchar(255) not null, primary key (cateID));
create table Chapter (chapterID int identity not null, courseID int not null, status bit, chapterName varchar(255) not null, primary key (chapterID));
create table Complete (completeID int identity not null, grade int, itemID int not null, learnerID int not null, status bit, date datetime2(6), comment varchar(255), homework varchar(255), primary key (completeID));
create table Course (cateID int not null, courseID int identity not null, instructorID int not null, levelID int not null, price float(24), rate int, status bit not null, viewer int, upload_date datetime2(6), Avatar varchar(255), description varchar(255), name varchar(255) not null, primary key (courseID));
create table Enrollment (courseID int not null, enrollmentID int identity not null, learnerID int not null, rate int, status bit, date datetime2(6), comment varchar(255), primary key (enrollmentID));
create table Instructor (instructorID int identity not null, rate int, status bit, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, role varchar(255), summarize varchar(255), primary key (instructorID));
create table Item (chapterID int not null, itemID int identity not null, status bit, content varchar(255), itemName varchar(255) not null, primary key (itemID));
create table Learner (learnerID int identity not null, status bit, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, role varchar(255), primary key (learnerID));
create table Level (levelID int identity not null, status bit, levelName varchar(255), primary key (levelID));
create table Post (cateID int not null, postID int identity not null, status bit, date datetime2(6), author varchar(255) not null, content varchar(255) not null, title varchar(255) not null, primary key (postID));
alter table Instructor add constraint UK_t6alh4njssx4tk4rlm6lu0odw unique (email);
alter table Learner add constraint UK_726l1bip7l5kr4ldte1s6nrwq unique (email);
alter table Chapter add constraint FK3r8caqrp38f0xtu9q848ii182 foreign key (courseID) references Course;
alter table Complete add constraint FK30s8c81mgta7rjud5vnk1ib6b foreign key (itemID) references Item;
alter table Complete add constraint FK3xogtphxl0v1v7o6jugtc3jjj foreign key (learnerID) references Learner;
alter table Course add constraint FK9k5rmqhqca41ewfod9n6bmuw9 foreign key (cateID) references Category;
alter table Course add constraint FKff7a1un6hp6ki4dtl9e4hru0k foreign key (instructorID) references Instructor;
alter table Course add constraint FK7isx9tia8g67e2q4okwitot5m foreign key (levelID) references Level;
alter table Enrollment add constraint FKfcxfn633c555js0hdapvjxyh6 foreign key (courseID) references Course;
alter table Enrollment add constraint FKb7tkpqrbudrcy318cli5nchbl foreign key (learnerID) references Learner;
alter table Item add constraint FKg9hgc86ngl1f7x8j8y51ai1ls foreign key (chapterID) references Chapter;
alter table Post add constraint FK202bahptojc0t82jc82ja9jmv foreign key (cateID) references Category;
